pipelines:
  default:  
    - parallel:
      - step:
          name: Build
          image: python:3.6.0
          caches:
            - pipenv
          script:
            - pip install --user pipenv
            - export PATH=$PATH:/root/.local/bin > /root/.profile
            - pipenv install --dev
      - step:
          name: Build JS
          image: node:10.15.0
          caches:
            - wgnode
          script:
            - npm install
    - parallel:
      - step:
          name: PyTest
          image: python:3.6.0
          caches:
            - pipenv
          script:            
            - pip install --user pipenv            
            - export PATH=$PATH:/root/.local/bin > /root/.profile
            - pipenv run pytest -c scripts/pytest.ini --cov --cov-config scripts/.coveragerc --junitxml=../test-results/xunit-result-master.xml;
      - step:
          name: Flake8
          image: python:3.6.0
          caches:
            - pipenv
          script:   
            - pip install --user pipenv            
            - export PATH=$PATH:/root/.local/bin > /root/.profile
            - pipenv run flake8 --config=scripts/.flake8
      - step:
          name: Pylint
          image: python:3.6.0
          caches:
            - pipenv
          script:   
            - pip install --user pipenv            
            - export PATH=$PATH:/root/.local/bin > /root/.profile
            - pipenv run pylint --rcfile=scripts/.pylintrc project
      - step:
          name: Jscpd report
          image: node:10.15.0
          caches:
            - wgnode
          script:
            - npm run jscpd --config scripts/.cpd.yaml || true; # "|| true" means "Allow to fail"
          artifacts:
            - report/*.html
      - step:
          name: ES Lint
          image: node:10.15.0
          caches:
            - wgnode
          script:
            - npm run eslint || true; # "|| true" means "Allow to fail"

definitions:
  caches:
    pipenv: /root/.local/share/virtualenvs
    wgnode: node_modules/
