version: "3.4"

services:
  django:
    build:
      context: .
      args:
        requirements: requirements/local.txt # Use local requirements!
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://development:development@db/development_db
      DJANGO_SETTINGS_MODULE: conf.settings.local
    depends_on:
      - db
    volumes:
      - ./:/app/code/
    ports:
      - "8000:8000"
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_USER: development
      POSTGRES_DB: development_db
    ports:
      - "5432:5432"
